#!/bin/bash

# Vercel 재배포 스크립트 - SSO 문제 해결용
# 개인 계정으로 새로 배포하는 방법

echo "🚀 Vercel 재배포 가이드"
echo "========================"
echo ""
echo "옵션 1: 현재 프로젝트에서 SSO 비활성화"
echo "----------------------------------------"
echo "1. https://vercel.com/dashboard 접속"
echo "2. Project Settings → Deployment Protection"
echo "3. 모든 보호 기능 OFF"
echo ""
echo "옵션 2: 새 개인 계정으로 배포 (권장)"
echo "----------------------------------------"
echo "1. 새 Vercel 개인 계정 생성"
echo "2. 아래 명령 실행:"
echo ""
echo "# Vercel CLI 설치"
echo "npm i -g vercel"
echo ""
echo "# 기존 연결 제거"
echo "rm -rf .vercel"
echo ""
echo "# 새 계정으로 로그인"
echo "vercel login"
echo ""
echo "# 프로젝트 배포 (개인 계정)"
echo "cd frontend"
echo "vercel --prod --public"
echo ""
echo "옵션 3: Netlify로 마이그레이션"
echo "----------------------------------------"
echo "# Netlify CLI 설치"
echo "npm i -g netlify-cli"
echo ""
echo "# Netlify 배포"
echo "cd frontend"
echo "npm run build"
echo "netlify deploy --prod --dir=build"
echo ""
echo "========================"
echo "배포 후 테스트 명령:"
echo "npm run test:e2e"