name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd frontend && npm ci
          cd ../backend && npm ci
          cd ../

      - name: Run tests (non-blocking)
        continue-on-error: true
        run: |
          echo "Running tests..."
          npm test || echo "Tests failed but continuing deployment (solo developer mode)"

      - name: Build frontend
        run: |
          cd frontend
          npm run build
          cd ../

      - name: Deploy to Vercel
        if: success()
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          cd frontend
          npx vercel --prod --token=$VERCEL_TOKEN --yes --scope team_ZRA46B1Ng8n027CYnt0PzJzr
          echo "✅ Successfully deployed to Vercel dot-platform project"

      - name: Create deployment tag
        if: success()
        run: |
          TAG_NAME="deploy-$(date +%Y%m%d-%H%M%S)"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "$TAG_NAME" -m "Production deployment on $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin "$TAG_NAME" || echo "Tag push requires permissions"

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deployment to production successful!"
            echo "🚀 Site is live at your Vercel production URL"
          else
            echo "⚠️ Deployment completed with warnings"
          fi